= Shinsetsu 新設

[quote,jisho.org]
____
Noun, Suru verb, No-adjective

1. establishing; founding; setting up; organizing; establishment
____

Shinsetsu is a browser plugin that takes the bookmark pain away from you.

== Installation

TBC

== Features

- Standard bookmark operations
- Cross-browser bookmark sync
- Tagging for easy searching & filtering
- Securing with passwords

== Rationale

A typical user will happily use the standard bookmark manager that comes with each browser, be it Chrome or Firefox.
And for most of the time, it fulfills lots of needs a user may have.

But, at the same time, it also leaves out lots of useful features that an advanced user may want to use.

Enter Shinsetsu, designed to be a replacement for the standard bookmark manager.

Now I can remove those bloody browser accounts...

== Contribution

This project for the most part is for my personal use. If you've found any bugs or issues, or want to have
additional features, please create an issue or PR.

== License
MIT License

Copyright (c) 2020 Rex Truong

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
